### ISSUE TITLE
Update plugin to work with Sketch 3.3

### ISSUE THREAD

**Issue by luloodesign** [tylergaw/icon-stamper#7]
I'm really loved this plugin. But sketch beta 3.3 always crashed when I use it. Hope you can fix this bug asap. Thanks!

**Comment by tylergaw** [comment]
Thanks for the report. I think things have changed in 3.3 with the way plugins work, will investigate and try to get a fix in before 3.3 is out of beta

**Comment by julien-c** [comment]
I can confirm that the plugings hangs indefinitely on Sketch (non-beta) version `Version 3.3 (11970)`

Hope this helps!

**Comment by pluwen** [comment]
sketch 3.3 have a new plugin format， so this plugin need to update

**Comment by whale** [comment]
@tylergaw thank you for the plugin and updating. Happy to donate if you have that kind of thing somewhere. I appreciate the time this saves me.

**Comment by tylergaw** [comment]
@whale Thanks! I've been super swamped lately, @bomberstudios just got this fixed for us in #8. Will get that merged in ASAP

**Comment by tylergaw** [comment]
I merged in #8 and gave this a quick test, but it wasn't working for me. Will have to take a closer look later.

**Comment by whale** [comment]
Dag. Thanks guys.

**Comment by bomberstudios** [comment]
Ah, sorry, I made a mistake there: where it says `context.document.currentView().centerRect(context.selection[0].rect());` you should use `context.document.currentView().centerRect(context.selection[0].absoluteRect().rect());`

Does it work if you do that, or are you seeing a different issue?

**Comment by blakeperdue** [comment]
@bomberstudios I tried making that change and it still hangs.

**Comment by bomberstudios** [comment]
@blakeperdue can you please share the steps you're following to make it hang so I can reproduce the issue (and hopefully fix it)? Thanks in advance!

**Comment by blakeperdue** [comment]
@bomberstudios Sure, here's what I did:

* Downloaded ZIP file for latest commit a13854f909
* Copied Icon Stamper.sketchplugin to plugins folder
* Edited Icon Stamper.sketchplugin with Sublime Text and changed line 49 from: `context.document.currentView().centerRect(context.selection[0].rect());` to `context.document.currentView().centerRect(context.selection[0].absoluteRect().rect());` per your comment above.
* Created new App Icon sketch file (File > New from template > iOS App Icon)
* Added my artwork: http://cl.ly/image/1x2G2b1J120k
* Clicked on the "Icon" folder that holds my artwork: http://cl.ly/image/0o3d0m413o2e
* Clicked on Plugins > Icon Stamper
* Nothing happens after that. I see no visible changes to the sketch canvas nor do I see any messages or alerts.

**Comment by tylergaw** [comment]
@bomberstudios I wasn't paying attention the first time I tested your fixes. The reason it didn't work for me because I hadn't updated to Sketch 3.3 yet, d'oh!

I have a new release tagged https://github.com/tylergaw/icon-stamper/releases/tag/v1.1.0

@blakeperdue Are you still running into the same issue? If so can you try it again with the Console.app open to see if there are any errors?

**Comment by tylergaw** [comment]
Fixed by #8 

New release for Sketch 3.3 in https://github.com/tylergaw/icon-stamper/releases/tag/v1.1.0

**Comment by blakeperdue** [comment]
I was actually running Sketch 3.2.2. Perhaps that was the cause of my problems.

**Comment by tylergaw** [comment]
Ah, yep that would have caused it to not work. I did the same thing. The 1.1.0 release above will work in Sketch 3.3.
